# Generated by Django 6.0.5 on 2026-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_profile_birthday_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='', upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
